//! Server handler for `smctl serve --mcp`.
//!
//! This module is deliberately thin: the MCP surface is generated by
//! `rmcp`'s `#[tool_router]` / `#[tool_handler]` macros, and the
//! business logic lives in the `smctl-*` library crates. The wiring
//! here covers
//!
//! - lifecycle MSGID emission (`SMCTL-0200` on bind, `SMCTL-0201` on
//!   shutdown, `SMCTL-0202..0204` around each tool call, `SMCTL-0206`
//!   on SSE transport bind / serve-loop failures);
//! - voice-conformant tool descriptions and error payloads per the
//!   `design-system-v1` contract;
//! - the full tool + resource surface for the smctl-mcp-v1 slice —
//!   20 tools across workspace / worktree / flow / spec / build and
//!   5 resources under the `smctl://` scheme.
//!
//! Transports: stdio via [`serve_stdio`], SSE / streamable HTTP via
//! [`serve_sse`] (loopback by default).

use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{
    CallToolRequestParams, CallToolResult, Content, Implementation, ListResourceTemplatesResult,
    ListResourcesResult, ListToolsResult, PaginatedRequestParams, ReadResourceRequestParams,
    ReadResourceResult, ServerCapabilities, ServerInfo, Tool,
};
use rmcp::service::RequestContext;
use rmcp::transport::streamable_http_server::{
    StreamableHttpServerConfig, StreamableHttpService, session::local::LocalSessionManager,
};
use rmcp::{ErrorData, RoleServer, ServerHandler, ServiceExt, tool, tool_router};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use smctl_log::MsgId;
use tokio_util::sync::CancellationToken;

use crate::resources;

/// Input schema for the `smctl_workspace_status` tool.
///
/// Keeping the input minimal is deliberate: the vertical slice only
/// needs to confirm the tool-call round-trip works. Additional filter
/// arguments will land with the fuller workspace tool surface (see
/// `tasks.md` — MCP Tools — Workspace).
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceStatusParams {
    /// Override the workspace root. Absolute path, or omit to use the
    /// root the server was started with.
    #[serde(default)]
    pub workspace: Option<String>,
}

/// Input schema for the `smctl_workspace_init` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceInitParams {
    /// Workspace name recorded in the manifest. Defaults to the last
    /// path segment of `path`.
    #[serde(default)]
    pub name: Option<String>,
    /// Absolute path where the workspace manifest is written. Defaults
    /// to the root the server was started with.
    #[serde(default)]
    pub path: Option<String>,
}

/// Input schema for the `smctl_workspace_add` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceAddParams {
    /// Git URL of the repo to register.
    pub url: String,
    /// Repo name in the manifest. Defaults to the last path segment of
    /// `url` with any `.git` suffix stripped.
    #[serde(default)]
    pub name: Option<String>,
    /// Local path relative to the workspace root. Defaults to `name`.
    #[serde(default)]
    pub path: Option<String>,
}

/// Input schema for the `smctl_workspace_remove` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceRemoveParams {
    /// Name of the repo to remove from the manifest.
    pub repo: String,
}

/// Input schema for the `smctl_workspace_sync` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceSyncParams {}

/// Input schema for the `smctl_worktree_add` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorktreeAddParams {
    /// Name of the worktree set; becomes the directory under the
    /// workspace's worktree base and the feature-branch suffix.
    pub name: String,
    /// Optional subset of repo names to include. Omit to include every
    /// repo in the manifest.
    #[serde(default)]
    pub repos: Option<Vec<String>>,
}

/// Input schema for the `smctl_worktree_list` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorktreeListParams {}

/// Input schema for the `smctl_worktree_remove` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorktreeRemoveParams {
    /// Name of the worktree set to remove.
    pub name: String,
    /// Force removal even when a worktree has uncommitted changes.
    #[serde(default)]
    pub force: Option<bool>,
}

/// Input schema for the `smctl_flow_init` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowInitParams {}

/// Input schema for flow feature/hotfix start tools.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowStartParams {
    /// Branch-name suffix; the full branch is the configured prefix
    /// followed by this value.
    pub name: String,
    /// Optional subset of repo names to act on. Omit to act on every
    /// repo.
    #[serde(default)]
    pub repos: Option<Vec<String>>,
}

/// Input schema for flow feature/hotfix finish tools.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowFinishParams {
    /// Branch-name suffix that was passed to `start`.
    pub name: String,
}

/// Input schema for the `smctl_flow_release_start` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowReleaseStartParams {
    /// Release version identifier appended to the release prefix.
    pub version: String,
    /// Optional subset of repo names to act on. Omit to act on every
    /// repo.
    #[serde(default)]
    pub repos: Option<Vec<String>>,
}

/// Input schema for the `smctl_flow_release_finish` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowReleaseFinishParams {
    /// Release version identifier that was passed to `release_start`.
    pub version: String,
}

/// Input schema for spec-by-name tools.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct SpecByNameParams {
    /// Spec identifier. Bare `name` works when unambiguous across
    /// registered repos; the qualified `repo:name` form picks one
    /// explicitly. `--repo` (the optional `repo` parameter) is
    /// equivalent sugar for prefixing.
    pub name: String,

    /// Optional repo selector. When set, the tool resolves the spec
    /// in that repo (equivalent to passing `repo:name`). Required for
    /// disambiguation when multiple repos declare the same name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
}

/// Input schema for the `smctl_spec_list` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct SpecListParams {}

/// Input schema for the `smctl_build` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct BuildParams {
    /// Build only this repo and its transitive dependencies. Omit to
    /// build every repo.
    #[serde(default)]
    pub repo: Option<String>,
    /// Run independent repos in parallel when true.
    #[serde(default)]
    pub parallel: Option<bool>,
    /// Run configured tests after each repo builds.
    #[serde(default)]
    pub test: Option<bool>,
    /// Run each repo's configured clean command before building.
    #[serde(default)]
    pub clean: Option<bool>,
}

/// Shared input shape for the four `smctl_verify_*` source-running
/// tools. `verify_discover` takes no arguments and uses
/// [`VerifyDiscoverParams`] instead.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct VerifyParams {
    /// Treat warnings as errors when computing the gate outcome.
    #[serde(default)]
    pub strict: Option<bool>,
}

/// Input schema for the `smctl_verify_discover` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct VerifyDiscoverParams {}

/// MCP server for smctl. Owns the workspace root plus the
/// auto-generated tool router.
#[derive(Debug, Clone)]
pub struct SmctlServer {
    workspace_root: Arc<PathBuf>,
    tool_router: ToolRouter<Self>,
}

impl SmctlServer {
    /// Create a new server bound to the given workspace root.
    pub fn new(workspace_root: PathBuf) -> Self {
        Self {
            workspace_root: Arc::new(workspace_root),
            tool_router: Self::tool_router(),
        }
    }

    /// Load the workspace manifest from the server's root, returning a
    /// voice-conformant three-part error if the manifest is missing.
    fn load_manifest(&self) -> Result<smctl_workspace::WorkspaceManifest, ErrorData> {
        smctl_workspace::WorkspaceManifest::load_from_root(&self.workspace_root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace manifest load failed. {e}. \
                     Run `smctl workspace init` in {} or start the server from a workspace root.",
                    self.workspace_root.display()
                ),
                None,
            )
        })
    }

    /// Build the per-repo `(name, openspec_dir)` slice the
    /// smctl-spec aggregating API expects. Mirrors the CLI's
    /// `Commands::Spec` prelude: every `[[repos]]` entry first,
    /// then a synthetic `_workspace` entry when the workspace root
    /// has its own openspec/, then a final fallback for fresh
    /// workspaces.
    fn spec_repos(&self, manifest: &smctl_workspace::WorkspaceManifest) -> Vec<(String, PathBuf)> {
        let mut repos: Vec<(String, PathBuf)> = manifest
            .repos
            .iter()
            .map(|r| {
                let path = r
                    .path
                    .clone()
                    .map(PathBuf::from)
                    .unwrap_or_else(|| self.workspace_root.join(&r.name));
                (r.name.clone(), path.join(&manifest.spec.openspec_dir))
            })
            .collect();
        smctl_spec::inject_synthetic_workspace_repo(
            &self.workspace_root,
            &manifest.spec.openspec_dir,
            &mut repos,
        );
        if repos.is_empty() {
            repos.push((
                "_workspace".to_string(),
                self.workspace_root.join(&manifest.spec.openspec_dir),
            ));
        }
        repos
    }

    /// Resolve a spec name against the per-repo slice, sugaring an
    /// optional `repo` field as the `repo:name` qualifier prefix.
    /// Errors surface as voice-conformant `ErrorData::invalid_params`
    /// so MCP clients see the three-part remediation in the JSON
    /// envelope.
    fn resolve_spec_ref(
        &self,
        repos: &[(String, PathBuf)],
        name: &str,
        repo: Option<&str>,
    ) -> Result<smctl_spec::RepoSpecRef, ErrorData> {
        let lookup = match repo {
            Some(r) if !name.contains(':') => format!("{r}:{name}"),
            _ => name.to_string(),
        };
        smctl_spec::find_spec_in_repos(repos, &lookup)
            .map_err(|e| ErrorData::invalid_params(format!("{e}"), None))
    }

    /// Serialize a value to pretty JSON, wrapping failures in a
    /// voice-conformant error.
    fn to_json_text(value: &serde_json::Value) -> Result<String, ErrorData> {
        serde_json::to_string_pretty(value).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Response serialization failed. {e}. \
                     Retry the tool call or run the equivalent `smctl` subcommand to reproduce."
                ),
                None,
            )
        })
    }

    /// Dispatch a `resources/read` request to the right reader.
    ///
    /// Returns `(ReadErrorKind, ErrorData)` on failure so the caller
    /// can record the classifier on `SMCTL-0208` before unwrapping the
    /// `ErrorData` that goes back to the client.
    async fn dispatch_read_resource(
        &self,
        uri: &str,
    ) -> Result<ReadResourceResult, (resources::ReadErrorKind, ErrorData)> {
        match uri {
            resources::URI_WORKSPACE_CONFIG => self.read_workspace_config(uri).await,
            resources::URI_WORKSPACE_STATUS => self.read_workspace_status(uri).await,
            resources::URI_FLOW_BRANCHES => self.read_flow_branches(uri).await,
            resources::URI_SPEC_LIST => self.read_spec_list(uri).await,
            other => {
                if let Some(name) = resources::parse_spec_tasks_uri(other) {
                    self.read_spec_tasks(other, name).await
                } else if other.starts_with("smctl://spec/") && other.ends_with("/tasks") {
                    // Matched the outer shape but the middle segment is
                    // empty or contains slashes.
                    Err((
                        resources::ReadErrorKind::InvalidUri,
                        ErrorData::invalid_params(
                            format!(
                                "Spec-tasks URI malformed. Got {other}. \
                                 Reissue as smctl://spec/<name>/tasks with a non-empty name."
                            ),
                            None,
                        ),
                    ))
                } else {
                    Err((
                        resources::ReadErrorKind::UnknownUri,
                        ErrorData::resource_not_found(
                            format!(
                                "No resource registered for {other}. \
                                 Call `resources/list` to enumerate supported URIs."
                            ),
                            None,
                        ),
                    ))
                }
            }
        }
    }

    async fn read_workspace_config(
        &self,
        uri: &str,
    ) -> Result<ReadResourceResult, (resources::ReadErrorKind, ErrorData)> {
        let content = resources::read_workspace_toml(&self.workspace_root)
            .map_err(|e| (resources::ReadErrorKind::ManifestMissing, e))?;
        Ok(resources::toml_result(uri, content))
    }

    async fn read_workspace_status(
        &self,
        uri: &str,
    ) -> Result<ReadResourceResult, (resources::ReadErrorKind, ErrorData)> {
        let manifest = self
            .load_manifest()
            .map_err(|e| (resources::ReadErrorKind::ManifestMissing, e))?;

        let mut statuses = Vec::with_capacity(manifest.repos.len());
        for repo in &manifest.repos {
            match smctl_workspace::repo_status(&self.workspace_root, repo) {
                Ok(status) => {
                    statuses.push(serde_json::to_value(&status).map_err(|e| {
                        (
                            resources::ReadErrorKind::SerializationFailed,
                            resources::read_failed(
                                uri,
                                format!(
                                    "Status serialization failed. {e}. \
                                     Retry the read or run `smctl workspace status` \
                                     to reproduce."
                                ),
                            ),
                        )
                    })?);
                }
                Err(e) => {
                    statuses.push(serde_json::json!({
                        "name": repo.name,
                        "error": format!("{e}"),
                    }));
                }
            }
        }

        let payload = serde_json::json!({ "repos": statuses });
        resources::json_result(uri, &payload)
            .map_err(|e| (resources::ReadErrorKind::SerializationFailed, e))
    }

    async fn read_flow_branches(
        &self,
        uri: &str,
    ) -> Result<ReadResourceResult, (resources::ReadErrorKind, ErrorData)> {
        let manifest = self
            .load_manifest()
            .map_err(|e| (resources::ReadErrorKind::ManifestMissing, e))?;
        let root = (*self.workspace_root).clone();

        let (features, releases, hotfixes) = tokio::task::spawn_blocking(move || {
            let features = smctl_flow::feature_list(&root, &manifest);
            let releases = smctl_flow::release_list(&root, &manifest);
            let hotfixes = smctl_flow::hotfix_list(&root, &manifest);
            (features, releases, hotfixes)
        })
        .await
        .map_err(|e| {
            (
                resources::ReadErrorKind::UpstreamFailed,
                resources::read_failed(
                    uri,
                    format!(
                        "Flow-branch enumeration task failed to join. {e}. \
                         Retry the read, or run `smctl flow feature list` to reproduce."
                    ),
                ),
            )
        })?;

        let features = features.map_err(|e| flow_upstream_error(uri, "feature", e))?;
        let releases = releases.map_err(|e| flow_upstream_error(uri, "release", e))?;
        let hotfixes = hotfixes.map_err(|e| flow_upstream_error(uri, "hotfix", e))?;

        let payload = serde_json::json!({
            "features": features,
            "releases": releases,
            "hotfixes": hotfixes,
        });
        resources::json_result(uri, &payload)
            .map_err(|e| (resources::ReadErrorKind::SerializationFailed, e))
    }

    async fn read_spec_list(
        &self,
        uri: &str,
    ) -> Result<ReadResourceResult, (resources::ReadErrorKind, ErrorData)> {
        let manifest = self
            .load_manifest()
            .map_err(|e| (resources::ReadErrorKind::ManifestMissing, e))?;
        let openspec_dir = self.workspace_root.join(&manifest.spec.openspec_dir);

        let specs = tokio::task::spawn_blocking(move || smctl_spec::list_specs(&openspec_dir))
            .await
            .map_err(|e| {
                (
                    resources::ReadErrorKind::UpstreamFailed,
                    resources::read_failed(
                        uri,
                        format!(
                            "Spec-list task failed to join. {e}. \
                             Retry the read, or run `smctl spec list` to reproduce."
                        ),
                    ),
                )
            })?
            .map_err(|e| {
                (
                    resources::ReadErrorKind::UpstreamFailed,
                    resources::read_failed(
                        uri,
                        format!(
                            "Spec list failed. {e}. \
                             Check that the openspec directory exists and is readable."
                        ),
                    ),
                )
            })?;

        let payload = serde_json::json!({ "specs": specs });
        resources::json_result(uri, &payload)
            .map_err(|e| (resources::ReadErrorKind::SerializationFailed, e))
    }

    async fn read_spec_tasks(
        &self,
        uri: &str,
        name: &str,
    ) -> Result<ReadResourceResult, (resources::ReadErrorKind, ErrorData)> {
        let manifest = self
            .load_manifest()
            .map_err(|e| (resources::ReadErrorKind::ManifestMissing, e))?;
        let openspec_dir = self.workspace_root.join(&manifest.spec.openspec_dir);
        let name_owned = name.to_string();

        let info = {
            let openspec_dir = openspec_dir.clone();
            let task_name = name_owned.clone();
            tokio::task::spawn_blocking(move || smctl_spec::spec_info(&openspec_dir, &task_name))
                .await
                .map_err(|e| {
                    (
                        resources::ReadErrorKind::UpstreamFailed,
                        resources::read_failed(
                            uri,
                            format!(
                                "Spec-info task failed to join. {e}. \
                                 Retry the read, or run `smctl spec list` to reproduce."
                            ),
                        ),
                    )
                })?
                .map_err(|e| {
                    (
                        resources::ReadErrorKind::UpstreamFailed,
                        ErrorData::resource_not_found(
                            format!(
                                "Spec {name_owned} not found. {e}. \
                                 Run `smctl spec list` to confirm the spec name."
                            ),
                            None,
                        ),
                    )
                })?
        };

        let tasks_path = info.path.join("tasks.md");
        let tasks_markdown = if tasks_path.exists() {
            std::fs::read_to_string(&tasks_path).map_err(|e| {
                (
                    resources::ReadErrorKind::UpstreamFailed,
                    resources::read_failed(
                        uri,
                        format!(
                            "Reading {} failed. {e}. \
                             Check filesystem permissions and retry.",
                            tasks_path.display()
                        ),
                    ),
                )
            })?
        } else {
            String::new()
        };

        let payload = serde_json::json!({
            "name": info.name,
            "phase": info.phase,
            "path": info.path,
            "has_proposal": info.has_proposal,
            "has_design": info.has_design,
            "has_tasks": info.has_tasks,
            "tasks_total": info.tasks_total,
            "tasks_done": info.tasks_done,
            "tasks_markdown": tasks_markdown,
        });
        resources::json_result(uri, &payload)
            .map_err(|e| (resources::ReadErrorKind::SerializationFailed, e))
    }
}

fn flow_upstream_error(
    uri: &str,
    branch_kind: &str,
    err: anyhow::Error,
) -> (resources::ReadErrorKind, ErrorData) {
    (
        resources::ReadErrorKind::UpstreamFailed,
        resources::read_failed(
            uri,
            format!(
                "Flow {branch_kind}-branch listing failed. {err}. \
                 Check that every repo in the manifest is cloned, then retry."
            ),
        ),
    )
}

#[tool_router]
impl SmctlServer {
    /// Report the status of every repo registered in the workspace.
    ///
    /// Returns a JSON array of `{ name, branch, clean, ahead, behind,
    /// modified_files }` objects. Uses the same `smctl_workspace`
    /// status helper the CLI calls.
    #[tool(
        name = "smctl_workspace_status",
        description = "Report the status of every repo in the workspace as JSON. Pass workspace to override the root the server was started with."
    )]
    async fn workspace_status(
        &self,
        Parameters(params): Parameters<WorkspaceStatusParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let root = params
            .workspace
            .as_deref()
            .map(PathBuf::from)
            .unwrap_or_else(|| (*self.workspace_root).clone());

        // Load the workspace manifest. Errors here are voice-conformant
        // three-part messages per design-system-v1 §"Error messages".
        let manifest = smctl_workspace::WorkspaceManifest::load_from_root(&root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace manifest load failed. {e}. \
                     Run `smctl workspace init` in {} or pass a valid workspace path.",
                    root.display()
                ),
                None,
            )
        })?;

        let mut statuses = Vec::with_capacity(manifest.repos.len());
        for repo in &manifest.repos {
            match smctl_workspace::repo_status(&root, repo) {
                Ok(status) => statuses.push(serde_json::to_value(&status).map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Status serialization failed. {e}. \
                             Run `smctl workspace status` to reproduce and capture the error."
                        ),
                        None,
                    )
                })?),
                Err(e) => {
                    // Surface per-repo failures inline so the caller
                    // sees a dirty-state error without losing results
                    // for other repos.
                    statuses.push(serde_json::json!({
                        "name": repo.name,
                        "error": format!("{e}"),
                    }));
                }
            }
        }

        let payload = serde_json::json!({ "repos": statuses });
        let text = serde_json::to_string_pretty(&payload).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Status serialization failed. {e}. \
                     Run `smctl workspace status --json` to reproduce."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(text)]))
    }

    /// Initialize a workspace manifest at the server's root (or a
    /// caller-provided path).
    #[tool(
        name = "smctl_workspace_init",
        description = "Initialize a workspace manifest. Writes .smctl/workspace.toml under the given path, or under the root the server was started with."
    )]
    async fn workspace_init(
        &self,
        Parameters(params): Parameters<WorkspaceInitParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let root = params
            .path
            .as_deref()
            .map(PathBuf::from)
            .unwrap_or_else(|| (*self.workspace_root).clone());
        let name = params.name.unwrap_or_else(|| {
            root.file_name()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_else(|| "workspace".to_string())
        });

        let manifest = smctl_workspace::init_workspace(&root, &name).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace init failed. {e}. \
                     Check write permissions on {} or pick a different path.",
                    root.display()
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({
            "name": manifest.workspace.name,
            "root": root.display().to_string(),
            "manifest_path": root.join(".smctl").join("workspace.toml").display().to_string(),
        });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Add a repo entry to the workspace manifest.
    #[tool(
        name = "smctl_workspace_add",
        description = "Add a repo to the workspace manifest. Pass the git URL; optionally override the repo name and local path."
    )]
    async fn workspace_add(
        &self,
        Parameters(params): Parameters<WorkspaceAddParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let mut manifest = self.load_manifest()?;
        let inferred_name = params.name.clone().unwrap_or_else(|| {
            params
                .url
                .rsplit('/')
                .next()
                .unwrap_or(&params.url)
                .trim_end_matches(".git")
                .to_string()
        });

        smctl_workspace::add_repo(
            &mut manifest,
            &inferred_name,
            &params.url,
            params.path.as_deref(),
        )
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Repo add failed. {e}. \
                     Run `smctl workspace status` to see the current repo list, then retry with a unique name."
                ),
                None,
            )
        })?;

        manifest.save_to_root(&self.workspace_root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Manifest save failed. {e}. \
                     Check write permissions on {} and retry.",
                    self.workspace_root.join(".smctl").display()
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({
            "name": inferred_name,
            "url": params.url,
            "path": params.path,
            "repos": manifest.repo_names(),
        });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Remove a repo entry from the workspace manifest.
    #[tool(
        name = "smctl_workspace_remove",
        description = "Remove a repo from the workspace manifest. Pass the repo name exactly as it appears in workspace.toml."
    )]
    async fn workspace_remove(
        &self,
        Parameters(params): Parameters<WorkspaceRemoveParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let mut manifest = self.load_manifest()?;
        smctl_workspace::remove_repo(&mut manifest, &params.repo).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Repo remove failed. {e}. \
                     Run `smctl workspace status` to confirm the repo name, then retry."
                ),
                None,
            )
        })?;

        manifest.save_to_root(&self.workspace_root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Manifest save failed. {e}. \
                     Check write permissions on {} and retry.",
                    self.workspace_root.join(".smctl").display()
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({
            "removed": params.repo,
            "repos": manifest.repo_names(),
        });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Fetch and fast-forward every repo in the workspace.
    #[tool(
        name = "smctl_workspace_sync",
        description = "Fast-forward pull every repo in the workspace. Skips repos that are not yet cloned; reports per-repo success or failure."
    )]
    async fn workspace_sync(
        &self,
        Parameters(_): Parameters<WorkspaceSyncParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();

        let results = tokio::task::spawn_blocking(move || {
            let mut out = Vec::with_capacity(manifest.repos.len());
            for repo in &manifest.repos {
                let repo_path = root.join(repo.local_path());
                if !repo_path.exists() {
                    out.push(serde_json::json!({
                        "repo": repo.name,
                        "status": "absent",
                        "message": "repo not cloned; skipped",
                    }));
                    continue;
                }
                let output = std::process::Command::new("git")
                    .args(["pull", "--ff-only"])
                    .current_dir(&repo_path)
                    .output();
                match output {
                    Ok(o) if o.status.success() => out.push(serde_json::json!({
                        "repo": repo.name,
                        "status": "synced",
                    })),
                    Ok(o) => out.push(serde_json::json!({
                        "repo": repo.name,
                        "status": "failed",
                        "message": String::from_utf8_lossy(&o.stderr).trim().to_string(),
                    })),
                    Err(e) => out.push(serde_json::json!({
                        "repo": repo.name,
                        "status": "failed",
                        "message": format!("{e}"),
                    })),
                }
            }
            out
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace sync task failed to join. {e}. \
                     Retry the tool call, or run `smctl workspace sync` to reproduce."
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({ "repos": results });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Create a linked worktree set across workspace repos.
    #[tool(
        name = "smctl_worktree_add",
        description = "Create a linked worktree set under the workspace's worktree base. Uses the configured feature prefix to name the branch."
    )]
    async fn worktree_add(
        &self,
        Parameters(params): Parameters<WorktreeAddParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let branch = format!("{}{}", manifest.flow.feature_prefix, params.name);
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();
        let repos = params.repos.clone();

        let infos = tokio::task::spawn_blocking(move || {
            smctl_workspace::worktree::add_worktree(
                &root,
                &manifest,
                &name,
                repos.as_deref(),
                &branch,
            )
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree add task failed to join. {e}. \
                     Retry the tool call, or run `smctl worktree add {}` to reproduce.",
                    params.name
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree add failed. {e}. \
                     Run `smctl worktree list` to inspect current worktrees, resolve the conflict, then retry."
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({ "name": params.name, "worktrees": infos });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// List every worktree set under the workspace's worktree base.
    #[tool(
        name = "smctl_worktree_list",
        description = "List worktree sets under the workspace's worktree base. Returns each set's repos with their checked-out branches."
    )]
    async fn worktree_list(
        &self,
        Parameters(_): Parameters<WorktreeListParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();

        let sets = tokio::task::spawn_blocking(move || {
            smctl_workspace::worktree::list_worktrees(&root, &manifest)
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree list task failed to join. {e}. \
                     Retry the tool call, or run `smctl worktree list` to reproduce."
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree list failed. {e}. \
                     Check the workspace's worktree base exists and is readable, then retry."
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({ "sets": sets });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Remove a worktree set across every repo in the workspace.
    #[tool(
        name = "smctl_worktree_remove",
        description = "Remove a worktree set from every repo in the workspace. Pass force=true to drop worktrees that have uncommitted changes."
    )]
    async fn worktree_remove(
        &self,
        Parameters(params): Parameters<WorktreeRemoveParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();
        let force = params.force.unwrap_or(false);

        tokio::task::spawn_blocking(move || {
            smctl_workspace::worktree::remove_worktree(&root, &manifest, &name, force)
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree remove task failed to join. {e}. \
                     Retry the tool call, or run `smctl worktree remove {}` to reproduce.",
                    params.name
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree remove failed. {e}. \
                     Run `smctl worktree list` to confirm the set name, or pass force=true to drop dirty worktrees."
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({ "removed": params.name, "force": force });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Initialize git flow branches across every repo.
    #[tool(
        name = "smctl_flow_init",
        description = "Ensure the configured develop branch exists in every repo. Creates it from the main branch when missing."
    )]
    async fn flow_init(
        &self,
        Parameters(_): Parameters<FlowInitParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();

        let result = tokio::task::spawn_blocking(move || smctl_flow::init(&root, &manifest))
            .await
            .map_err(|e| {
                ErrorData::internal_error(
                    format!(
                        "Flow init task failed to join. {e}. \
                         Retry the tool call, or run `smctl flow init` to reproduce."
                    ),
                    None,
                )
            })?
            .map_err(|e| {
                ErrorData::internal_error(
                    format!(
                        "Flow init failed. {e}. \
                         Run `smctl workspace status` to confirm every repo is cloned, then retry."
                    ),
                    None,
                )
            })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Start a feature branch across the selected repos.
    #[tool(
        name = "smctl_flow_feature_start",
        description = "Start a feature branch across the selected repos. Uses the configured feature prefix; base branch is develop."
    )]
    async fn flow_feature_start(
        &self,
        Parameters(params): Parameters<FlowStartParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();
        let repos = params.repos.clone();

        let result = tokio::task::spawn_blocking(move || {
            smctl_flow::feature_start(&root, &manifest, &name, repos.as_deref())
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Feature start task failed to join. {e}. \
                     Retry the tool call, or run `smctl flow feature start {}` to reproduce.",
                    params.name
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Feature start failed. {e}. \
                     Run `smctl flow init` first if the develop branch is missing, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Finish a feature branch: merge into develop across every repo.
    #[tool(
        name = "smctl_flow_feature_finish",
        description = "Merge a feature branch into develop across every repo. Pass the same name that was used for feature_start."
    )]
    async fn flow_feature_finish(
        &self,
        Parameters(params): Parameters<FlowFinishParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();

        let result =
            tokio::task::spawn_blocking(move || smctl_flow::feature_finish(&root, &manifest, &name))
                .await
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Feature finish task failed to join. {e}. \
                             Retry the tool call, or run `smctl flow feature finish {}` to reproduce.",
                            params.name
                        ),
                        None,
                    )
                })?
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Feature finish failed. {e}. \
                             Resolve the merge conflict in the reported repo, commit, then retry."
                        ),
                        None,
                    )
                })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Start a release branch across the selected repos.
    #[tool(
        name = "smctl_flow_release_start",
        description = "Start a release branch across the selected repos. Uses the configured release prefix; base branch is develop."
    )]
    async fn flow_release_start(
        &self,
        Parameters(params): Parameters<FlowReleaseStartParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let version = params.version.clone();
        let repos = params.repos.clone();

        let result = tokio::task::spawn_blocking(move || {
            smctl_flow::release_start(&root, &manifest, &version, repos.as_deref())
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Release start task failed to join. {e}. \
                     Retry the tool call, or run `smctl flow release start {}` to reproduce.",
                    params.version
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Release start failed. {e}. \
                     Run `smctl flow init` first if develop is missing, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Finish a release: merge into main and develop across every repo.
    #[tool(
        name = "smctl_flow_release_finish",
        description = "Merge a release branch into main and develop across every repo. Pass the same version that was used for release_start."
    )]
    async fn flow_release_finish(
        &self,
        Parameters(params): Parameters<FlowReleaseFinishParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let version = params.version.clone();

        let result = tokio::task::spawn_blocking(move || {
            smctl_flow::release_finish(&root, &manifest, &version)
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Release finish task failed to join. {e}. \
                     Retry the tool call, or run `smctl flow release finish {}` to reproduce.",
                    params.version
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Release finish failed. {e}. \
                     Resolve the merge conflict in the reported repo, commit, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Start a hotfix branch across the selected repos.
    #[tool(
        name = "smctl_flow_hotfix_start",
        description = "Start a hotfix branch across the selected repos. Uses the configured hotfix prefix; base branch is main."
    )]
    async fn flow_hotfix_start(
        &self,
        Parameters(params): Parameters<FlowStartParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();
        let repos = params.repos.clone();

        let result = tokio::task::spawn_blocking(move || {
            smctl_flow::hotfix_start(&root, &manifest, &name, repos.as_deref())
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Hotfix start task failed to join. {e}. \
                     Retry the tool call, or run `smctl flow hotfix start {}` to reproduce.",
                    params.name
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Hotfix start failed. {e}. \
                     Run `smctl workspace status` to confirm main is present in every repo, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Finish a hotfix: merge into main and develop across every repo.
    #[tool(
        name = "smctl_flow_hotfix_finish",
        description = "Merge a hotfix branch into main and develop across every repo. Pass the same name that was used for hotfix_start."
    )]
    async fn flow_hotfix_finish(
        &self,
        Parameters(params): Parameters<FlowFinishParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();

        let result =
            tokio::task::spawn_blocking(move || smctl_flow::hotfix_finish(&root, &manifest, &name))
                .await
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Hotfix finish task failed to join. {e}. \
                             Retry the tool call, or run `smctl flow hotfix finish {}` to reproduce.",
                            params.name
                        ),
                        None,
                    )
                })?
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Hotfix finish failed. {e}. \
                             Resolve the merge conflict in the reported repo, commit, then retry."
                        ),
                        None,
                    )
                })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Scaffold a new OpenSpec change folder.
    #[tool(
        name = "smctl_spec_new",
        description = "Scaffold a new OpenSpec change under openspec/changes/<name>. Writes proposal.md, design.md, and tasks.md stubs."
    )]
    async fn spec_new(
        &self,
        Parameters(params): Parameters<SpecByNameParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let repos = self.spec_repos(&manifest);

        // Pick the target repo. When `repo` is set, find that entry's
        // openspec_dir. Otherwise default to the smctl_home repo
        // when one is declared, else the single registered repo,
        // else error with a remediation listing the candidates.
        let target_dir = if let Some(want) = params.repo.as_deref() {
            repos
                .iter()
                .find(|(r, _)| r == want)
                .map(|(_, p)| p.clone())
                .ok_or_else(|| {
                    let known: Vec<&str> = repos.iter().map(|(r, _)| r.as_str()).collect();
                    ErrorData::invalid_params(
                        format!(
                            "Repo '{want}' is not registered in this workspace. \
                             Known repos: {known:?}. \
                             Pass `repo` with one of those, or `smctl workspace add` the repo first."
                        ),
                        None,
                    )
                })?
        } else if let Some(home) = manifest.repos.iter().find(|r| r.smctl_home) {
            repos
                .iter()
                .find(|(r, _)| r == &home.name)
                .map(|(_, p)| p.clone())
                .unwrap_or_else(|| self.workspace_root.join(&manifest.spec.openspec_dir))
        } else if repos.len() == 1 {
            repos[0].1.clone()
        } else {
            let known: Vec<&str> = repos.iter().map(|(r, _)| r.as_str()).collect();
            return Err(ErrorData::invalid_params(
                format!(
                    "No target repo for `smctl_spec_new`. \
                     The workspace has multiple registered repos and no `[[repos]]` entry declares `smctl_home = true`. \
                     Pass `repo` with one of: {known:?}."
                ),
                None,
            ));
        };

        let name = params.name.clone();
        let info = tokio::task::spawn_blocking(move || smctl_spec::new_spec(&target_dir, &name))
            .await
            .map_err(|e| {
                ErrorData::internal_error(
                    format!(
                        "Spec new task failed to join. {e}. \
                         Retry the tool call, or run `smctl spec new {}` to reproduce.",
                        params.name
                    ),
                    None,
                )
            })?
            .map_err(|e| {
                ErrorData::internal_error(
                    format!(
                        "Spec new failed. {e}. \
                         Run `smctl spec list` to see existing specs, then retry with a unique name."
                    ),
                    None,
                )
            })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&info).unwrap_or_default())?,
        )]))
    }

    /// Validate an OpenSpec change for completeness.
    #[tool(
        name = "smctl_spec_validate",
        description = "Validate an OpenSpec change. Reports missing documents and required sections; returns valid=true when every check passes."
    )]
    async fn spec_validate(
        &self,
        Parameters(params): Parameters<SpecByNameParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let repos = self.spec_repos(&manifest);
        let r = self.resolve_spec_ref(&repos, &params.name, params.repo.as_deref())?;

        let openspec_dir = r.openspec_dir.clone();
        let name = r.name.clone();
        let qualified = r.qualified();

        let result =
            tokio::task::spawn_blocking(move || smctl_spec::validate(&openspec_dir, &name))
                .await
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Spec validate task failed to join. {e}. \
                         Retry the tool call, or run `smctl spec validate {qualified}` to reproduce."
                        ),
                        None,
                    )
                })?
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Spec validate failed. {e}. \
                         Run `smctl spec list` to confirm the spec name, then retry."
                        ),
                        None,
                    )
                })?;

        // Wrap the ValidationResult with the resolved repo so the
        // tool envelope tells the caller which repo was validated.
        let payload = serde_json::json!({
            "repo": r.repo,
            "name": r.name,
            "qualified": qualified,
            "result": result,
        });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Archive a completed OpenSpec change.
    #[tool(
        name = "smctl_spec_archive",
        description = "Archive a completed OpenSpec change. Moves it into openspec/changes/archive/<date>-<name>."
    )]
    async fn spec_archive(
        &self,
        Parameters(params): Parameters<SpecByNameParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let repos = self.spec_repos(&manifest);
        let r = self.resolve_spec_ref(&repos, &params.name, params.repo.as_deref())?;

        let openspec_dir = r.openspec_dir.clone();
        let name = r.name.clone();
        let qualified = r.qualified();

        let dest =
            tokio::task::spawn_blocking(move || smctl_spec::archive_in_repo(&openspec_dir, &name))
                .await
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Spec archive task failed to join. {e}. \
                             Retry the tool call, or run `smctl spec archive {qualified}` to reproduce."
                        ),
                        None,
                    )
                })?
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Spec archive failed. {e}. \
                             Run `smctl spec validate {qualified}` to confirm the spec exists and is complete, then retry."
                        ),
                        None,
                    )
                })?;

        let payload = serde_json::json!({
            "repo": r.repo,
            "name": r.name,
            "qualified": qualified,
            "archive_path": dest.display().to_string(),
        });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// List every OpenSpec change in the workspace.
    #[tool(
        name = "smctl_spec_list",
        description = "List every OpenSpec change in the workspace, including archived ones. Returns each spec's phase and task-completion counts."
    )]
    async fn spec_list(
        &self,
        Parameters(_): Parameters<SpecListParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let repos = self.spec_repos(&manifest);

        let specs = tokio::task::spawn_blocking(move || smctl_spec::list_specs_across(&repos))
            .await
            .map_err(|e| {
                ErrorData::internal_error(
                    format!(
                        "Spec list task failed to join. {e}. \
                         Retry the tool call, or run `smctl spec list` to reproduce."
                    ),
                    None,
                )
            })?
            .map_err(|e| {
                ErrorData::internal_error(
                    format!(
                        "Spec list failed. {e}. \
                         Check that the registered repos and their openspec/ trees are readable, then retry."
                    ),
                    None,
                )
            })?;

        let payload = serde_json::json!({ "specs": specs });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Build repos in dependency order.
    #[tool(
        name = "smctl_build",
        description = "Build repos in dependency order. Pass repo to scope the build; enable parallel, test, or clean as needed."
    )]
    async fn build(
        &self,
        Parameters(params): Parameters<BuildParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let repo = params.repo.clone();
        let parallel = params.parallel.unwrap_or(false);
        let run_tests = params.test.unwrap_or(false);
        let clean_first = params.clean.unwrap_or(false);

        let report = tokio::task::spawn_blocking(move || {
            if parallel {
                smctl_build::build_parallel(
                    &root,
                    &manifest,
                    repo.as_deref(),
                    run_tests,
                    clean_first,
                )
            } else {
                smctl_build::build(&root, &manifest, repo.as_deref(), run_tests, clean_first)
            }
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Build task failed to join. {e}. \
                     Retry the tool call, or run `smctl build` to reproduce."
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Build failed. {e}. \
                     Inspect the reported repo's build output, fix the error, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&report).unwrap_or_default())?,
        )]))
    }

    /// Run the Cedar policy verifier and return the report as JSON.
    #[tool(
        name = "smctl_verify_policy",
        description = "Run Cedar policy verification against [verify.policy].sources from workspace.toml. Returns a VerifyReport JSON with per-source pass/fail rows."
    )]
    async fn verify_policy(
        &self,
        Parameters(params): Parameters<VerifyParams>,
    ) -> Result<CallToolResult, ErrorData> {
        self.run_verifier("policy", params.strict.unwrap_or(false))
    }

    /// Run the TLA+ model checker against `[verify.model].specs`.
    #[tool(
        name = "smctl_verify_model",
        description = "Run TLA+ model checking against [verify.model].specs from workspace.toml. Returns a VerifyReport JSON; surfaces tool_missing when tlc isn't on PATH."
    )]
    async fn verify_model(
        &self,
        Parameters(params): Parameters<VerifyParams>,
    ) -> Result<CallToolResult, ErrorData> {
        self.run_verifier("model", params.strict.unwrap_or(false))
    }

    /// Run Lean 4 proofs against `[verify.proof].roots`.
    #[tool(
        name = "smctl_verify_proof",
        description = "Run Lean 4 proofs against [verify.proof].roots from workspace.toml. Lake packages build with lake; loose .lean trees check per file with lean --json, and proofs containing sorry fail their row. Returns a VerifyReport JSON; surfaces tool_missing when lean/lake isn't on PATH."
    )]
    async fn verify_proof(
        &self,
        Parameters(params): Parameters<VerifyParams>,
    ) -> Result<CallToolResult, ErrorData> {
        self.run_verifier("proof", params.strict.unwrap_or(false))
    }

    /// Run SPIN/Promela protocol verification against
    /// `[verify.protocol].specs`.
    #[tool(
        name = "smctl_verify_protocol",
        description = "Run SPIN/Promela protocol verification against [verify.protocol].specs from workspace.toml. Returns a VerifyReport JSON; surfaces tool_missing when spin isn't on PATH."
    )]
    async fn verify_protocol(
        &self,
        Parameters(params): Parameters<VerifyParams>,
    ) -> Result<CallToolResult, ErrorData> {
        self.run_verifier("protocol", params.strict.unwrap_or(false))
    }

    /// Enumerate which verifiers are reachable on PATH.
    #[tool(
        name = "smctl_verify_discover",
        description = "Enumerate every smctl-verify verifier and report whether its underlying tool is reachable on PATH (Cedar, TLA+, Lean 4, SPIN)."
    )]
    async fn verify_discover(
        &self,
        Parameters(_params): Parameters<VerifyDiscoverParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let registry = smctl_verify::Registry::with_default_verifiers();
        let entries: Vec<_> = registry
            .iter()
            .map(|v| {
                serde_json::json!({
                    "verifier": v.name(),
                    "discovery": v.discover(),
                })
            })
            .collect();
        let payload = serde_json::Value::Array(entries);
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }
}

impl SmctlServer {
    /// Shared body for `verify_policy` / `model` / `proof` /
    /// `protocol` — load the manifest, build the per-verb context,
    /// dispatch to the registry, return the report as JSON.
    fn run_verifier(&self, verb: &str, strict: bool) -> Result<CallToolResult, ErrorData> {
        let workspace_root = (*self.workspace_root).clone();
        let manifest = smctl_workspace::WorkspaceManifest::load_from_root(&workspace_root).ok();

        let repos: std::collections::BTreeMap<String, PathBuf> = match manifest.as_ref() {
            Some(m) => m
                .repos
                .iter()
                .map(|r| {
                    let path = r
                        .path
                        .clone()
                        .map(PathBuf::from)
                        .unwrap_or_else(|| workspace_root.join(&r.name));
                    (r.name.clone(), path)
                })
                .collect(),
            None => {
                let mut m = std::collections::BTreeMap::new();
                m.insert(".".into(), workspace_root.clone());
                m
            }
        };

        let ctx = smctl_verify::VerifyContext {
            workspace_root,
            repos,
            manifest: smctl_verify::manifest_from_workspace(
                manifest.as_ref().and_then(|m| m.verify.as_ref()),
                verb,
            ),
            strict,
            verifier_filter: None,
        };

        let registry = smctl_verify::Registry::with_default_verifiers();
        let verifier = registry.find(verb).ok_or_else(|| {
            ErrorData::internal_error(
                format!(
                    "Verifier '{verb}' is not registered. \
                     This is a smctl-mcp bug — please file an issue against ModelGate."
                ),
                None,
            )
        })?;
        let report = verifier.run(&ctx);
        let payload = serde_json::to_value(&report).unwrap_or_default();
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }
}

impl ServerHandler for SmctlServer {
    fn get_info(&self) -> ServerInfo {
        // Advertise both tools and resources. Resources do not support
        // `subscribe` or `listChanged` notifications yet — the MCP
        // surface is pure polling. When the subscription path lands
        // (see `tasks.md`) flip on `enable_resources_subscribe` and
        // `enable_resources_list_changed` here.
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::new("smctl", env!("CARGO_PKG_VERSION")))
        .with_instructions(
            "Expose smctl workspace, flow, spec, and build operations to MCP clients. \
             Call tools under the smctl_* namespace for mutations; read resources under \
             the smctl:// scheme for workspace state. Run `smctl serve --mcp --stdio` \
             from your workspace root."
                .to_string(),
        )
    }

    // Manually override `call_tool` so every invocation emits the
    // SMCTL-0202 / SMCTL-0203 / SMCTL-0204 catalog events. The router
    // (built by `#[tool_router]`) still does the dispatch.
    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, ErrorData> {
        let tool_name = request.name.clone().into_owned();
        let request_id = format!("{}", context.id);
        let started = Instant::now();

        tracing::info!(
            msgid = %MsgId::McpToolCalled,
            tool = %tool_name,
            request_id = %request_id,
            "tool call received"
        );

        let tcc = ToolCallContext::new(self, request, context);
        let outcome = self.tool_router.call(tcc).await;
        let duration_ms = started.elapsed().as_millis() as u64;

        match &outcome {
            Ok(result) if result.is_error.unwrap_or(false) => {
                tracing::error!(
                    msgid = %MsgId::McpToolFailed,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    error_kind = "tool_returned_error",
                    remediation = %tool_remediation(&tool_name),
                    "tool call returned an error payload"
                );
            }
            Ok(_) => {
                tracing::info!(
                    msgid = %MsgId::McpToolCompleted,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    "tool call completed"
                );
            }
            Err(err) => {
                tracing::error!(
                    msgid = %MsgId::McpToolFailed,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    error_kind = %format!("{:?}", err.code),
                    remediation = %tool_remediation(&tool_name),
                    "tool call failed before dispatch"
                );
            }
        }

        outcome
    }

    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, ErrorData> {
        Ok(ListToolsResult {
            tools: self.tool_router.list_all(),
            meta: None,
            next_cursor: None,
        })
    }

    fn get_tool(&self, name: &str) -> Option<Tool> {
        self.tool_router.get(name).cloned()
    }

    // -- Resources --------------------------------------------------
    //
    // rmcp 1.5 has no `#[resource_router]` macro analogous to the tool
    // surface, so each dispatch is written out longhand. The static
    // list and templates come from `crate::resources`; the read path
    // emits SMCTL-0207 on success / SMCTL-0208 on failure, mirroring
    // the SMCTL-0203 / SMCTL-0204 tool-call pair.

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, ErrorData> {
        Ok(ListResourcesResult::with_all_items(
            resources::static_resources(),
        ))
    }

    async fn list_resource_templates(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, ErrorData> {
        Ok(ListResourceTemplatesResult::with_all_items(
            resources::resource_templates(),
        ))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, ErrorData> {
        let uri = request.uri.clone();
        let request_id = format!("{}", context.id);
        let started = Instant::now();

        let outcome = self.dispatch_read_resource(&uri).await;
        let duration_ms = started.elapsed().as_millis() as u64;

        match &outcome {
            Ok(_) => {
                tracing::info!(
                    msgid = %MsgId::McpResourceRead,
                    uri = %uri,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    "resource read completed"
                );
            }
            Err((kind, err)) => {
                tracing::error!(
                    msgid = %MsgId::McpResourceReadFailed,
                    uri = %uri,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    error_kind = kind.as_str(),
                    remediation = %remediation_for(*kind, &uri),
                    "resource read failed: {}",
                    err.message
                );
            }
        }

        outcome.map_err(|(_kind, err)| err)
    }
}

/// Map a tool name to the `remediation` field recorded on `SMCTL-0204`.
///
/// Each value names an executable `smctl` subcommand per the
/// `design-system-v1` error rubric. Tools fall back to a generic
/// remediation when their direct CLI analogue is not obvious; the
/// caller can always re-run with the matching `smctl` subcommand to
/// reproduce under a human-friendly formatter.
fn tool_remediation(tool: &str) -> &'static str {
    match tool {
        "smctl_workspace_status" => "run `smctl workspace status` to reproduce",
        "smctl_workspace_init" => "run `smctl workspace init` in a writable directory",
        "smctl_workspace_add" => "run `smctl workspace status`, then retry with a unique repo name",
        "smctl_workspace_remove" => "run `smctl workspace status` to confirm the repo name",
        "smctl_workspace_sync" => "run `smctl workspace sync` to reproduce per-repo errors",
        "smctl_worktree_add" => "run `smctl worktree list`, resolve the conflict, then retry",
        "smctl_worktree_list" => "run `smctl worktree list` to reproduce",
        "smctl_worktree_remove" => {
            "run `smctl worktree list`, then retry with force=true if needed"
        }
        "smctl_flow_init" => "run `smctl flow init` to reproduce",
        "smctl_flow_feature_start" => {
            "run `smctl flow init`, then retry `smctl flow feature start`"
        }
        "smctl_flow_feature_finish" => {
            "resolve the merge conflict, then retry `smctl flow feature finish`"
        }
        "smctl_flow_release_start" => {
            "run `smctl flow init`, then retry `smctl flow release start`"
        }
        "smctl_flow_release_finish" => {
            "resolve the merge conflict, then retry `smctl flow release finish`"
        }
        "smctl_flow_hotfix_start" => {
            "run `smctl workspace status`, then retry `smctl flow hotfix start`"
        }
        "smctl_flow_hotfix_finish" => {
            "resolve the merge conflict, then retry `smctl flow hotfix finish`"
        }
        "smctl_spec_new" => "run `smctl spec list`, then retry `smctl spec new` with a unique name",
        "smctl_spec_validate" => "run `smctl spec list` to confirm the spec name",
        "smctl_spec_archive" => "run `smctl spec validate <name>`, then retry `smctl spec archive`",
        "smctl_spec_list" => "run `smctl spec list` to reproduce",
        "smctl_build" => "run `smctl build` to reproduce",
        _ => "re-run the tool call with `smctl <subcommand>` to reproduce",
    }
}

/// Map a [`resources::ReadErrorKind`] to the `remediation` field
/// recorded on `SMCTL-0208`. Each value names an executable `smctl`
/// subcommand per the `design-system-v1` error rubric.
fn remediation_for(kind: resources::ReadErrorKind, _uri: &str) -> String {
    match kind {
        resources::ReadErrorKind::UnknownUri => {
            "list `resources/list` or call the matching smctl subcommand".to_string()
        }
        resources::ReadErrorKind::InvalidUri => {
            "reissue the read as smctl://spec/<name>/tasks with a concrete spec name".to_string()
        }
        resources::ReadErrorKind::ManifestMissing => {
            "run `smctl workspace init` in the workspace root".to_string()
        }
        resources::ReadErrorKind::UpstreamFailed => {
            "run the equivalent `smctl` subcommand to capture the underlying error".to_string()
        }
        resources::ReadErrorKind::SerializationFailed => {
            "retry the read; the state may have been captured mid-transition".to_string()
        }
    }
}

/// Start the MCP server on stdio and block until the peer closes the
/// transport.
///
/// Emits `SMCTL-0200` once the transport is bound, `SMCTL-0201` on
/// graceful shutdown. `SMCTL-0205` (unexpected client disconnect) and
/// `SMCTL-0206` (transport fatal) are declared in the catalog but are
/// not reachable on stdio — stdio close is the shutdown signal. The
/// SSE transport ([`serve_sse`]) owns the SMCTL-0205 / SMCTL-0206
/// emission sites.
pub async fn serve_stdio(workspace_root: PathBuf) -> anyhow::Result<()> {
    let server = SmctlServer::new(workspace_root);
    let transport = rmcp::transport::stdio();

    tracing::info!(
        msgid = %MsgId::McpServerStarted,
        transport = "stdio",
        "MCP server bound to stdio"
    );

    let running = server.serve(transport).await?;

    // Block until the peer closes stdin. `waiting` returns the reason;
    // for stdio the only path back is a clean close.
    let reason = running.waiting().await?;

    tracing::info!(
        msgid = %MsgId::McpServerStopped,
        reason = %format!("{reason:?}"),
        "MCP server stopped"
    );

    Ok(())
}

/// Start the MCP server on SSE / streamable-HTTP and block until the
/// TCP listener closes.
///
/// Binds to `addr`, wraps an [`rmcp`] `StreamableHttpService` in an axum
/// router, and serves the MCP endpoint at `/mcp`. Each client connection
/// runs as its own session via `LocalSessionManager`; session lifetimes
/// are tracked by rmcp.
///
/// MSGID emission:
///
/// - `SMCTL-0200 McpServerStarted` once the TCP listener is bound,
///   carrying `transport="sse"` and `listen_addr=<local_addr>`.
/// - `SMCTL-0201 McpServerStopped` on graceful shutdown.
/// - `SMCTL-0206 McpTransportFatal` if `TcpListener::bind` fails or the
///   axum serve-loop returns an error.
///
/// `SMCTL-0205 McpClientDisconnected` is emitted per-session by rmcp's
/// own session lifecycle — the streamable-HTTP server spawns a task per
/// session that logs unexpected closes, so the transport-level wrapper
/// here does not re-emit. If session-level disconnect tracing is
/// required later, layer a session manager wrapper over
/// `LocalSessionManager`.
pub async fn serve_sse(workspace_root: PathBuf, addr: SocketAddr) -> anyhow::Result<()> {
    let cancel = CancellationToken::new();
    let server = SmctlServer::new(workspace_root);

    // `StreamableHttpService::new` expects a factory that produces a
    // fresh handler per session; clone the prebuilt server (it is cheap
    // — the workspace root is an Arc and the tool router is a Clone).
    let service = StreamableHttpService::new(
        move || Ok(server.clone()),
        Arc::new(LocalSessionManager::default()),
        StreamableHttpServerConfig::default().with_cancellation_token(cancel.child_token()),
    );

    let router = axum::Router::new().nest_service("/mcp", service);

    let listener = match tokio::net::TcpListener::bind(addr).await {
        Ok(listener) => listener,
        Err(e) => {
            tracing::error!(
                msgid = %MsgId::McpTransportFatal,
                transport = "sse",
                error = %e,
                "SSE listener bind failed"
            );
            return Err(anyhow::anyhow!(
                "SSE listener bind failed at {addr}. {e}. \
                 Re-run `smctl serve --mcp --sse --port <n>` with a free port."
            ));
        }
    };

    let local_addr = listener.local_addr()?;

    tracing::info!(
        msgid = %MsgId::McpServerStarted,
        transport = "sse",
        listen_addr = %local_addr,
        "MCP server bound to SSE"
    );

    let serve_result = axum::serve(listener, router)
        .with_graceful_shutdown({
            let cancel = cancel.clone();
            async move { cancel.cancelled().await }
        })
        .await;

    match serve_result {
        Ok(()) => {
            tracing::info!(
                msgid = %MsgId::McpServerStopped,
                transport = "sse",
                reason = "listener_closed",
                "MCP server stopped"
            );
            Ok(())
        }
        Err(e) => {
            tracing::error!(
                msgid = %MsgId::McpTransportFatal,
                transport = "sse",
                error = %e,
                "SSE listener crashed"
            );
            Err(anyhow::anyhow!(
                "SSE listener crashed. {e}. \
                 Re-run `smctl serve --mcp --sse --port <n>` after inspecting the stderr log."
            ))
        }
    }
}
