//! Server handler for `smctl serve --mcp`.
//!
//! This module is deliberately thin: the MCP surface is generated by
//! `rmcp`'s `#[tool_router]` / `#[tool_handler]` macros, and the
//! business logic lives in `smctl_workspace`. The wiring here covers
//!
//! - lifecycle MSGID emission (`SMCTL-0200` on bind, `SMCTL-0201` on
//!   shutdown, `SMCTL-0202..0204` around each tool call);
//! - voice-conformant tool descriptions and error payloads per the
//!   `design-system-v1` contract;
//! - exactly one tool, `smctl_workspace_status`, matching the
//!   smctl-mcp-v1 vertical slice.
//!
//! SSE / streamable-HTTP transports and the remaining tool surface are
//! tracked as follow-ups in `openspec/changes/smctl-mcp-v1/tasks.md`.

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{
    CallToolRequestParams, CallToolResult, Content, Implementation, ListToolsResult,
    PaginatedRequestParams, ServerCapabilities, ServerInfo, Tool,
};
use rmcp::service::RequestContext;
use rmcp::{ErrorData, RoleServer, ServerHandler, ServiceExt, tool, tool_router};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use smctl_log::MsgId;

/// Input schema for the `smctl_workspace_status` tool.
///
/// Keeping the input minimal is deliberate: the vertical slice only
/// needs to confirm the tool-call round-trip works. Additional filter
/// arguments will land with the fuller workspace tool surface (see
/// `tasks.md` — MCP Tools — Workspace).
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceStatusParams {
    /// Override the workspace root. Absolute path, or omit to use the
    /// root the server was started with.
    #[serde(default)]
    pub workspace: Option<String>,
}

/// MCP server for smctl. Owns the workspace root plus the
/// auto-generated tool router.
#[derive(Debug, Clone)]
pub struct SmctlServer {
    workspace_root: Arc<PathBuf>,
    tool_router: ToolRouter<Self>,
}

impl SmctlServer {
    /// Create a new server bound to the given workspace root.
    pub fn new(workspace_root: PathBuf) -> Self {
        Self {
            workspace_root: Arc::new(workspace_root),
            tool_router: Self::tool_router(),
        }
    }
}

#[tool_router]
impl SmctlServer {
    /// Report the status of every repo registered in the workspace.
    ///
    /// Returns a JSON array of `{ name, branch, clean, ahead, behind,
    /// modified_files }` objects. Uses the same `smctl_workspace`
    /// status helper the CLI calls.
    #[tool(
        name = "smctl_workspace_status",
        description = "Report the status of every repo in the workspace as JSON. Pass workspace to override the root the server was started with."
    )]
    async fn workspace_status(
        &self,
        Parameters(params): Parameters<WorkspaceStatusParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let root = params
            .workspace
            .as_deref()
            .map(PathBuf::from)
            .unwrap_or_else(|| (*self.workspace_root).clone());

        // Load the workspace manifest. Errors here are voice-conformant
        // three-part messages per design-system-v1 §"Error messages".
        let manifest = smctl_workspace::WorkspaceManifest::load_from_root(&root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace manifest load failed. {e}. \
                     Run `smctl workspace init` in {} or pass a valid workspace path.",
                    root.display()
                ),
                None,
            )
        })?;

        let mut statuses = Vec::with_capacity(manifest.repos.len());
        for repo in &manifest.repos {
            match smctl_workspace::repo_status(&root, repo) {
                Ok(status) => statuses.push(serde_json::to_value(&status).map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Status serialization failed. {e}. \
                             Run `smctl workspace status` to reproduce and capture the error."
                        ),
                        None,
                    )
                })?),
                Err(e) => {
                    // Surface per-repo failures inline so the caller
                    // sees a dirty-state error without losing results
                    // for other repos.
                    statuses.push(serde_json::json!({
                        "name": repo.name,
                        "error": format!("{e}"),
                    }));
                }
            }
        }

        let payload = serde_json::json!({ "repos": statuses });
        let text = serde_json::to_string_pretty(&payload).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Status serialization failed. {e}. \
                     Run `smctl workspace status --json` to reproduce."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(text)]))
    }
}

impl ServerHandler for SmctlServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("smctl", env!("CARGO_PKG_VERSION")))
            .with_instructions(
                "Expose smctl workspace, flow, spec, and build operations to MCP clients. \
                 v1 ships one tool, smctl_workspace_status; run `smctl serve --mcp --stdio` \
                 from your workspace root."
                    .to_string(),
            )
    }

    // Manually override `call_tool` so every invocation emits the
    // SMCTL-0202 / SMCTL-0203 / SMCTL-0204 catalog events. The router
    // (built by `#[tool_router]`) still does the dispatch.
    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, ErrorData> {
        let tool_name = request.name.clone().into_owned();
        let request_id = format!("{}", context.id);
        let started = Instant::now();

        tracing::info!(
            msgid = %MsgId::McpToolCalled,
            tool = %tool_name,
            request_id = %request_id,
            "tool call received"
        );

        let tcc = ToolCallContext::new(self, request, context);
        let outcome = self.tool_router.call(tcc).await;
        let duration_ms = started.elapsed().as_millis() as u64;

        match &outcome {
            Ok(result) if result.is_error.unwrap_or(false) => {
                tracing::error!(
                    msgid = %MsgId::McpToolFailed,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    error_kind = "tool_returned_error",
                    "tool call returned an error payload"
                );
            }
            Ok(_) => {
                tracing::info!(
                    msgid = %MsgId::McpToolCompleted,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    "tool call completed"
                );
            }
            Err(err) => {
                tracing::error!(
                    msgid = %MsgId::McpToolFailed,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    error_kind = %format!("{:?}", err.code),
                    "tool call failed before dispatch"
                );
            }
        }

        outcome
    }

    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, ErrorData> {
        Ok(ListToolsResult {
            tools: self.tool_router.list_all(),
            meta: None,
            next_cursor: None,
        })
    }

    fn get_tool(&self, name: &str) -> Option<Tool> {
        self.tool_router.get(name).cloned()
    }
}

/// Start the MCP server on stdio and block until the peer closes the
/// transport.
///
/// Emits `SMCTL-0200` once the transport is bound, `SMCTL-0201` on
/// graceful shutdown. `SMCTL-0205` (unexpected client disconnect) and
/// `SMCTL-0206` (transport fatal) are declared in the catalog but are
/// not reachable on the stdio-only slice — stdio close is the
/// shutdown signal. See `tasks.md` for the follow-up wiring.
pub async fn serve_stdio(workspace_root: PathBuf) -> anyhow::Result<()> {
    let server = SmctlServer::new(workspace_root);
    let transport = rmcp::transport::stdio();

    tracing::info!(
        msgid = %MsgId::McpServerStarted,
        transport = "stdio",
        "MCP server bound to stdio"
    );

    let running = server.serve(transport).await?;

    // Block until the peer closes stdin. `waiting` returns the reason;
    // for stdio the only path back is a clean close.
    let reason = running.waiting().await?;

    tracing::info!(
        msgid = %MsgId::McpServerStopped,
        reason = %format!("{reason:?}"),
        "MCP server stopped"
    );

    // TODO(smctl-mcp-v1 follow-up): emit SMCTL-0205 when rmcp surfaces
    // an unexpected-disconnect reason distinct from a clean close, and
    // SMCTL-0206 from the SSE / HTTP transport error paths once those
    // land. See openspec/changes/smctl-mcp-v1/tasks.md — "Spec drift
    // and follow-ups".
    let _ = (MsgId::McpClientDisconnected, MsgId::McpTransportFatal);

    Ok(())
}
