//! Server handler for `smctl serve --mcp`.
//!
//! This module is deliberately thin: the MCP surface is generated by
//! `rmcp`'s `#[tool_router]` / `#[tool_handler]` macros, and the
//! business logic lives in `smctl_workspace`. The wiring here covers
//!
//! - lifecycle MSGID emission (`SMCTL-0200` on bind, `SMCTL-0201` on
//!   shutdown, `SMCTL-0202..0204` around each tool call);
//! - voice-conformant tool descriptions and error payloads per the
//!   `design-system-v1` contract;
//! - exactly one tool, `smctl_workspace_status`, matching the
//!   smctl-mcp-v1 vertical slice.
//!
//! SSE / streamable-HTTP transports and the remaining tool surface are
//! tracked as follow-ups in `openspec/changes/smctl-mcp-v1/tasks.md`.

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::ToolCallContext;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{
    CallToolRequestParams, CallToolResult, Content, Implementation, ListToolsResult,
    PaginatedRequestParams, ServerCapabilities, ServerInfo, Tool,
};
use rmcp::service::RequestContext;
use rmcp::{ErrorData, RoleServer, ServerHandler, ServiceExt, tool, tool_router};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use smctl_log::MsgId;

/// Input schema for the `smctl_workspace_status` tool.
///
/// Keeping the input minimal is deliberate: the vertical slice only
/// needs to confirm the tool-call round-trip works. Additional filter
/// arguments will land with the fuller workspace tool surface (see
/// `tasks.md` — MCP Tools — Workspace).
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceStatusParams {
    /// Override the workspace root. Absolute path, or omit to use the
    /// root the server was started with.
    #[serde(default)]
    pub workspace: Option<String>,
}

/// Input schema for the `smctl_workspace_init` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceInitParams {
    /// Workspace name recorded in the manifest. Defaults to the last
    /// path segment of `path`.
    #[serde(default)]
    pub name: Option<String>,
    /// Absolute path where the workspace manifest is written. Defaults
    /// to the root the server was started with.
    #[serde(default)]
    pub path: Option<String>,
}

/// Input schema for the `smctl_workspace_add` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceAddParams {
    /// Git URL of the repo to register.
    pub url: String,
    /// Repo name in the manifest. Defaults to the last path segment of
    /// `url` with any `.git` suffix stripped.
    #[serde(default)]
    pub name: Option<String>,
    /// Local path relative to the workspace root. Defaults to `name`.
    #[serde(default)]
    pub path: Option<String>,
}

/// Input schema for the `smctl_workspace_remove` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceRemoveParams {
    /// Name of the repo to remove from the manifest.
    pub repo: String,
}

/// Input schema for the `smctl_workspace_sync` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceSyncParams {}

/// Input schema for the `smctl_worktree_add` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorktreeAddParams {
    /// Name of the worktree set; becomes the directory under the
    /// workspace's worktree base and the feature-branch suffix.
    pub name: String,
    /// Optional subset of repo names to include. Omit to include every
    /// repo in the manifest.
    #[serde(default)]
    pub repos: Option<Vec<String>>,
}

/// Input schema for the `smctl_worktree_list` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorktreeListParams {}

/// Input schema for the `smctl_worktree_remove` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct WorktreeRemoveParams {
    /// Name of the worktree set to remove.
    pub name: String,
    /// Force removal even when a worktree has uncommitted changes.
    #[serde(default)]
    pub force: Option<bool>,
}

/// Input schema for the `smctl_flow_init` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowInitParams {}

/// Input schema for flow feature/hotfix start tools.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowStartParams {
    /// Branch-name suffix; the full branch is the configured prefix
    /// followed by this value.
    pub name: String,
    /// Optional subset of repo names to act on. Omit to act on every
    /// repo.
    #[serde(default)]
    pub repos: Option<Vec<String>>,
}

/// Input schema for flow feature/hotfix finish tools.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowFinishParams {
    /// Branch-name suffix that was passed to `start`.
    pub name: String,
}

/// Input schema for the `smctl_flow_release_start` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowReleaseStartParams {
    /// Release version identifier appended to the release prefix.
    pub version: String,
    /// Optional subset of repo names to act on. Omit to act on every
    /// repo.
    #[serde(default)]
    pub repos: Option<Vec<String>>,
}

/// Input schema for the `smctl_flow_release_finish` tool.
#[derive(Debug, Default, Serialize, Deserialize, JsonSchema)]
pub struct FlowReleaseFinishParams {
    /// Release version identifier that was passed to `release_start`.
    pub version: String,
}

/// MCP server for smctl. Owns the workspace root plus the
/// auto-generated tool router.
#[derive(Debug, Clone)]
pub struct SmctlServer {
    workspace_root: Arc<PathBuf>,
    tool_router: ToolRouter<Self>,
}

impl SmctlServer {
    /// Create a new server bound to the given workspace root.
    pub fn new(workspace_root: PathBuf) -> Self {
        Self {
            workspace_root: Arc::new(workspace_root),
            tool_router: Self::tool_router(),
        }
    }

    /// Load the workspace manifest from the server's root, returning a
    /// voice-conformant three-part error if the manifest is missing.
    fn load_manifest(&self) -> Result<smctl_workspace::WorkspaceManifest, ErrorData> {
        smctl_workspace::WorkspaceManifest::load_from_root(&self.workspace_root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace manifest load failed. {e}. \
                     Run `smctl workspace init` in {} or start the server from a workspace root.",
                    self.workspace_root.display()
                ),
                None,
            )
        })
    }

    /// Serialize a value to pretty JSON, wrapping failures in a
    /// voice-conformant error.
    fn to_json_text(value: &serde_json::Value) -> Result<String, ErrorData> {
        serde_json::to_string_pretty(value).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Response serialization failed. {e}. \
                     Retry the tool call or run the equivalent `smctl` subcommand to reproduce."
                ),
                None,
            )
        })
    }
}

#[tool_router]
impl SmctlServer {
    /// Report the status of every repo registered in the workspace.
    ///
    /// Returns a JSON array of `{ name, branch, clean, ahead, behind,
    /// modified_files }` objects. Uses the same `smctl_workspace`
    /// status helper the CLI calls.
    #[tool(
        name = "smctl_workspace_status",
        description = "Report the status of every repo in the workspace as JSON. Pass workspace to override the root the server was started with."
    )]
    async fn workspace_status(
        &self,
        Parameters(params): Parameters<WorkspaceStatusParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let root = params
            .workspace
            .as_deref()
            .map(PathBuf::from)
            .unwrap_or_else(|| (*self.workspace_root).clone());

        // Load the workspace manifest. Errors here are voice-conformant
        // three-part messages per design-system-v1 §"Error messages".
        let manifest = smctl_workspace::WorkspaceManifest::load_from_root(&root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace manifest load failed. {e}. \
                     Run `smctl workspace init` in {} or pass a valid workspace path.",
                    root.display()
                ),
                None,
            )
        })?;

        let mut statuses = Vec::with_capacity(manifest.repos.len());
        for repo in &manifest.repos {
            match smctl_workspace::repo_status(&root, repo) {
                Ok(status) => statuses.push(serde_json::to_value(&status).map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Status serialization failed. {e}. \
                             Run `smctl workspace status` to reproduce and capture the error."
                        ),
                        None,
                    )
                })?),
                Err(e) => {
                    // Surface per-repo failures inline so the caller
                    // sees a dirty-state error without losing results
                    // for other repos.
                    statuses.push(serde_json::json!({
                        "name": repo.name,
                        "error": format!("{e}"),
                    }));
                }
            }
        }

        let payload = serde_json::json!({ "repos": statuses });
        let text = serde_json::to_string_pretty(&payload).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Status serialization failed. {e}. \
                     Run `smctl workspace status --json` to reproduce."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(text)]))
    }

    /// Initialize a workspace manifest at the server's root (or a
    /// caller-provided path).
    #[tool(
        name = "smctl_workspace_init",
        description = "Initialize a workspace manifest. Writes .smctl/workspace.toml under the given path, or under the root the server was started with."
    )]
    async fn workspace_init(
        &self,
        Parameters(params): Parameters<WorkspaceInitParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let root = params
            .path
            .as_deref()
            .map(PathBuf::from)
            .unwrap_or_else(|| (*self.workspace_root).clone());
        let name = params.name.unwrap_or_else(|| {
            root.file_name()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_else(|| "workspace".to_string())
        });

        let manifest = smctl_workspace::init_workspace(&root, &name).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace init failed. {e}. \
                     Check write permissions on {} or pick a different path.",
                    root.display()
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({
            "name": manifest.workspace.name,
            "root": root.display().to_string(),
            "manifest_path": root.join(".smctl").join("workspace.toml").display().to_string(),
        });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Add a repo entry to the workspace manifest.
    #[tool(
        name = "smctl_workspace_add",
        description = "Add a repo to the workspace manifest. Pass the git URL; optionally override the repo name and local path."
    )]
    async fn workspace_add(
        &self,
        Parameters(params): Parameters<WorkspaceAddParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let mut manifest = self.load_manifest()?;
        let inferred_name = params.name.clone().unwrap_or_else(|| {
            params
                .url
                .rsplit('/')
                .next()
                .unwrap_or(&params.url)
                .trim_end_matches(".git")
                .to_string()
        });

        smctl_workspace::add_repo(
            &mut manifest,
            &inferred_name,
            &params.url,
            params.path.as_deref(),
        )
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Repo add failed. {e}. \
                     Run `smctl workspace status` to see the current repo list, then retry with a unique name."
                ),
                None,
            )
        })?;

        manifest.save_to_root(&self.workspace_root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Manifest save failed. {e}. \
                     Check write permissions on {} and retry.",
                    self.workspace_root.join(".smctl").display()
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({
            "name": inferred_name,
            "url": params.url,
            "path": params.path,
            "repos": manifest.repo_names(),
        });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Remove a repo entry from the workspace manifest.
    #[tool(
        name = "smctl_workspace_remove",
        description = "Remove a repo from the workspace manifest. Pass the repo name exactly as it appears in workspace.toml."
    )]
    async fn workspace_remove(
        &self,
        Parameters(params): Parameters<WorkspaceRemoveParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let mut manifest = self.load_manifest()?;
        smctl_workspace::remove_repo(&mut manifest, &params.repo).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Repo remove failed. {e}. \
                     Run `smctl workspace status` to confirm the repo name, then retry."
                ),
                None,
            )
        })?;

        manifest.save_to_root(&self.workspace_root).map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Manifest save failed. {e}. \
                     Check write permissions on {} and retry.",
                    self.workspace_root.join(".smctl").display()
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({
            "removed": params.repo,
            "repos": manifest.repo_names(),
        });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Fetch and fast-forward every repo in the workspace.
    #[tool(
        name = "smctl_workspace_sync",
        description = "Fast-forward pull every repo in the workspace. Skips repos that are not yet cloned; reports per-repo success or failure."
    )]
    async fn workspace_sync(
        &self,
        Parameters(_): Parameters<WorkspaceSyncParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();

        let results = tokio::task::spawn_blocking(move || {
            let mut out = Vec::with_capacity(manifest.repos.len());
            for repo in &manifest.repos {
                let repo_path = root.join(repo.local_path());
                if !repo_path.exists() {
                    out.push(serde_json::json!({
                        "repo": repo.name,
                        "status": "absent",
                        "message": "repo not cloned; skipped",
                    }));
                    continue;
                }
                let output = std::process::Command::new("git")
                    .args(["pull", "--ff-only"])
                    .current_dir(&repo_path)
                    .output();
                match output {
                    Ok(o) if o.status.success() => out.push(serde_json::json!({
                        "repo": repo.name,
                        "status": "synced",
                    })),
                    Ok(o) => out.push(serde_json::json!({
                        "repo": repo.name,
                        "status": "failed",
                        "message": String::from_utf8_lossy(&o.stderr).trim().to_string(),
                    })),
                    Err(e) => out.push(serde_json::json!({
                        "repo": repo.name,
                        "status": "failed",
                        "message": format!("{e}"),
                    })),
                }
            }
            out
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Workspace sync task failed to join. {e}. \
                     Retry the tool call, or run `smctl workspace sync` to reproduce."
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({ "repos": results });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Create a linked worktree set across workspace repos.
    #[tool(
        name = "smctl_worktree_add",
        description = "Create a linked worktree set under the workspace's worktree base. Uses the configured feature prefix to name the branch."
    )]
    async fn worktree_add(
        &self,
        Parameters(params): Parameters<WorktreeAddParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let branch = format!("{}{}", manifest.flow.feature_prefix, params.name);
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();
        let repos = params.repos.clone();

        let infos = tokio::task::spawn_blocking(move || {
            smctl_workspace::worktree::add_worktree(
                &root,
                &manifest,
                &name,
                repos.as_deref(),
                &branch,
            )
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree add task failed to join. {e}. \
                     Retry the tool call, or run `smctl worktree add {}` to reproduce.",
                    params.name
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree add failed. {e}. \
                     Run `smctl worktree list` to inspect current worktrees, resolve the conflict, then retry."
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({ "name": params.name, "worktrees": infos });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// List every worktree set under the workspace's worktree base.
    #[tool(
        name = "smctl_worktree_list",
        description = "List worktree sets under the workspace's worktree base. Returns each set's repos with their checked-out branches."
    )]
    async fn worktree_list(
        &self,
        Parameters(_): Parameters<WorktreeListParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();

        let sets = tokio::task::spawn_blocking(move || {
            smctl_workspace::worktree::list_worktrees(&root, &manifest)
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree list task failed to join. {e}. \
                     Retry the tool call, or run `smctl worktree list` to reproduce."
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree list failed. {e}. \
                     Check the workspace's worktree base exists and is readable, then retry."
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({ "sets": sets });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Remove a worktree set across every repo in the workspace.
    #[tool(
        name = "smctl_worktree_remove",
        description = "Remove a worktree set from every repo in the workspace. Pass force=true to drop worktrees that have uncommitted changes."
    )]
    async fn worktree_remove(
        &self,
        Parameters(params): Parameters<WorktreeRemoveParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();
        let force = params.force.unwrap_or(false);

        tokio::task::spawn_blocking(move || {
            smctl_workspace::worktree::remove_worktree(&root, &manifest, &name, force)
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree remove task failed to join. {e}. \
                     Retry the tool call, or run `smctl worktree remove {}` to reproduce.",
                    params.name
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Worktree remove failed. {e}. \
                     Run `smctl worktree list` to confirm the set name, or pass force=true to drop dirty worktrees."
                ),
                None,
            )
        })?;

        let payload = serde_json::json!({ "removed": params.name, "force": force });
        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&payload)?,
        )]))
    }

    /// Initialize git flow branches across every repo.
    #[tool(
        name = "smctl_flow_init",
        description = "Ensure the configured develop branch exists in every repo. Creates it from the main branch when missing."
    )]
    async fn flow_init(
        &self,
        Parameters(_): Parameters<FlowInitParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();

        let result = tokio::task::spawn_blocking(move || smctl_flow::init(&root, &manifest))
            .await
            .map_err(|e| {
                ErrorData::internal_error(
                    format!(
                        "Flow init task failed to join. {e}. \
                         Retry the tool call, or run `smctl flow init` to reproduce."
                    ),
                    None,
                )
            })?
            .map_err(|e| {
                ErrorData::internal_error(
                    format!(
                        "Flow init failed. {e}. \
                         Run `smctl workspace status` to confirm every repo is cloned, then retry."
                    ),
                    None,
                )
            })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Start a feature branch across the selected repos.
    #[tool(
        name = "smctl_flow_feature_start",
        description = "Start a feature branch across the selected repos. Uses the configured feature prefix; base branch is develop."
    )]
    async fn flow_feature_start(
        &self,
        Parameters(params): Parameters<FlowStartParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();
        let repos = params.repos.clone();

        let result = tokio::task::spawn_blocking(move || {
            smctl_flow::feature_start(&root, &manifest, &name, repos.as_deref())
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Feature start task failed to join. {e}. \
                     Retry the tool call, or run `smctl flow feature start {}` to reproduce.",
                    params.name
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Feature start failed. {e}. \
                     Run `smctl flow init` first if the develop branch is missing, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Finish a feature branch: merge into develop across every repo.
    #[tool(
        name = "smctl_flow_feature_finish",
        description = "Merge a feature branch into develop across every repo. Pass the same name that was used for feature_start."
    )]
    async fn flow_feature_finish(
        &self,
        Parameters(params): Parameters<FlowFinishParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();

        let result =
            tokio::task::spawn_blocking(move || smctl_flow::feature_finish(&root, &manifest, &name))
                .await
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Feature finish task failed to join. {e}. \
                             Retry the tool call, or run `smctl flow feature finish {}` to reproduce.",
                            params.name
                        ),
                        None,
                    )
                })?
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Feature finish failed. {e}. \
                             Resolve the merge conflict in the reported repo, commit, then retry."
                        ),
                        None,
                    )
                })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Start a release branch across the selected repos.
    #[tool(
        name = "smctl_flow_release_start",
        description = "Start a release branch across the selected repos. Uses the configured release prefix; base branch is develop."
    )]
    async fn flow_release_start(
        &self,
        Parameters(params): Parameters<FlowReleaseStartParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let version = params.version.clone();
        let repos = params.repos.clone();

        let result = tokio::task::spawn_blocking(move || {
            smctl_flow::release_start(&root, &manifest, &version, repos.as_deref())
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Release start task failed to join. {e}. \
                     Retry the tool call, or run `smctl flow release start {}` to reproduce.",
                    params.version
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Release start failed. {e}. \
                     Run `smctl flow init` first if develop is missing, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Finish a release: merge into main and develop across every repo.
    #[tool(
        name = "smctl_flow_release_finish",
        description = "Merge a release branch into main and develop across every repo. Pass the same version that was used for release_start."
    )]
    async fn flow_release_finish(
        &self,
        Parameters(params): Parameters<FlowReleaseFinishParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let version = params.version.clone();

        let result = tokio::task::spawn_blocking(move || {
            smctl_flow::release_finish(&root, &manifest, &version)
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Release finish task failed to join. {e}. \
                     Retry the tool call, or run `smctl flow release finish {}` to reproduce.",
                    params.version
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Release finish failed. {e}. \
                     Resolve the merge conflict in the reported repo, commit, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Start a hotfix branch across the selected repos.
    #[tool(
        name = "smctl_flow_hotfix_start",
        description = "Start a hotfix branch across the selected repos. Uses the configured hotfix prefix; base branch is main."
    )]
    async fn flow_hotfix_start(
        &self,
        Parameters(params): Parameters<FlowStartParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();
        let repos = params.repos.clone();

        let result = tokio::task::spawn_blocking(move || {
            smctl_flow::hotfix_start(&root, &manifest, &name, repos.as_deref())
        })
        .await
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Hotfix start task failed to join. {e}. \
                     Retry the tool call, or run `smctl flow hotfix start {}` to reproduce.",
                    params.name
                ),
                None,
            )
        })?
        .map_err(|e| {
            ErrorData::internal_error(
                format!(
                    "Hotfix start failed. {e}. \
                     Run `smctl workspace status` to confirm main is present in every repo, then retry."
                ),
                None,
            )
        })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }

    /// Finish a hotfix: merge into main and develop across every repo.
    #[tool(
        name = "smctl_flow_hotfix_finish",
        description = "Merge a hotfix branch into main and develop across every repo. Pass the same name that was used for hotfix_start."
    )]
    async fn flow_hotfix_finish(
        &self,
        Parameters(params): Parameters<FlowFinishParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let manifest = self.load_manifest()?;
        let root = (*self.workspace_root).clone();
        let name = params.name.clone();

        let result =
            tokio::task::spawn_blocking(move || smctl_flow::hotfix_finish(&root, &manifest, &name))
                .await
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Hotfix finish task failed to join. {e}. \
                             Retry the tool call, or run `smctl flow hotfix finish {}` to reproduce.",
                            params.name
                        ),
                        None,
                    )
                })?
                .map_err(|e| {
                    ErrorData::internal_error(
                        format!(
                            "Hotfix finish failed. {e}. \
                             Resolve the merge conflict in the reported repo, commit, then retry."
                        ),
                        None,
                    )
                })?;

        Ok(CallToolResult::success(vec![Content::text(
            Self::to_json_text(&serde_json::to_value(&result).unwrap_or_default())?,
        )]))
    }
}

impl ServerHandler for SmctlServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("smctl", env!("CARGO_PKG_VERSION")))
            .with_instructions(
                "Expose smctl workspace, flow, spec, and build operations to MCP clients. \
                 v1 ships one tool, smctl_workspace_status; run `smctl serve --mcp --stdio` \
                 from your workspace root."
                    .to_string(),
            )
    }

    // Manually override `call_tool` so every invocation emits the
    // SMCTL-0202 / SMCTL-0203 / SMCTL-0204 catalog events. The router
    // (built by `#[tool_router]`) still does the dispatch.
    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, ErrorData> {
        let tool_name = request.name.clone().into_owned();
        let request_id = format!("{}", context.id);
        let started = Instant::now();

        tracing::info!(
            msgid = %MsgId::McpToolCalled,
            tool = %tool_name,
            request_id = %request_id,
            "tool call received"
        );

        let tcc = ToolCallContext::new(self, request, context);
        let outcome = self.tool_router.call(tcc).await;
        let duration_ms = started.elapsed().as_millis() as u64;

        match &outcome {
            Ok(result) if result.is_error.unwrap_or(false) => {
                tracing::error!(
                    msgid = %MsgId::McpToolFailed,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    error_kind = "tool_returned_error",
                    "tool call returned an error payload"
                );
            }
            Ok(_) => {
                tracing::info!(
                    msgid = %MsgId::McpToolCompleted,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    "tool call completed"
                );
            }
            Err(err) => {
                tracing::error!(
                    msgid = %MsgId::McpToolFailed,
                    tool = %tool_name,
                    request_id = %request_id,
                    duration_ms = duration_ms,
                    error_kind = %format!("{:?}", err.code),
                    "tool call failed before dispatch"
                );
            }
        }

        outcome
    }

    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, ErrorData> {
        Ok(ListToolsResult {
            tools: self.tool_router.list_all(),
            meta: None,
            next_cursor: None,
        })
    }

    fn get_tool(&self, name: &str) -> Option<Tool> {
        self.tool_router.get(name).cloned()
    }
}

/// Start the MCP server on stdio and block until the peer closes the
/// transport.
///
/// Emits `SMCTL-0200` once the transport is bound, `SMCTL-0201` on
/// graceful shutdown. `SMCTL-0205` (unexpected client disconnect) and
/// `SMCTL-0206` (transport fatal) are declared in the catalog but are
/// not reachable on the stdio-only slice — stdio close is the
/// shutdown signal. See `tasks.md` for the follow-up wiring.
pub async fn serve_stdio(workspace_root: PathBuf) -> anyhow::Result<()> {
    let server = SmctlServer::new(workspace_root);
    let transport = rmcp::transport::stdio();

    tracing::info!(
        msgid = %MsgId::McpServerStarted,
        transport = "stdio",
        "MCP server bound to stdio"
    );

    let running = server.serve(transport).await?;

    // Block until the peer closes stdin. `waiting` returns the reason;
    // for stdio the only path back is a clean close.
    let reason = running.waiting().await?;

    tracing::info!(
        msgid = %MsgId::McpServerStopped,
        reason = %format!("{reason:?}"),
        "MCP server stopped"
    );

    // TODO(smctl-mcp-v1 follow-up): emit SMCTL-0205 when rmcp surfaces
    // an unexpected-disconnect reason distinct from a clean close, and
    // SMCTL-0206 from the SSE / HTTP transport error paths once those
    // land. See openspec/changes/smctl-mcp-v1/tasks.md — "Spec drift
    // and follow-ups".
    let _ = (MsgId::McpClientDisconnected, MsgId::McpTransportFatal);

    Ok(())
}
